max_depth: 
  low: 3
  high: 18
  q: 1
gamma:
  low: 1
  high: 9
reg_alpha:
  low: 40
  high: 180
  q: 1
reg_lambda:
  low: 0
  high: 1
colsample_bytree:
  low: 0.5
  high: 1
min_child_weight:
  low: 0
  high: 10
  q: 1
n_estimators: 180
seed: 0
use_label_encoder: False
objective: "binary:logistic"
eval_metric: auc
early_stopping_rounds: 10